# Generated by Django 2.2.5 on 2021-02-15 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('duration', models.IntegerField(help_text='Duration to update price (in minutes)')),
                ('price_per_duration', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('rate', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='pages.Bonus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_bonus', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_times', to='pages.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_tables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('items_quantity_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('items_quantity_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('price', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
