# Generated by Django 2.2.5 on 2020-06-23 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_auto_20200623_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservedTables',
            new_name='ReservedTable',
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('items_quantity_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('address', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('items_quantity_list', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('price', models.FloatField()),
                ('delivery_fee', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
