# Generated by Django 2.2.5 on 2020-06-22 10:03

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(max_length=500, upload_to=menu.models.cuisine_image_upload_path)),
            ],
        ),
    ]
