# Generated by Django 2.2.5 on 2020-06-22 10:34

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField()),
                ('total_orders', models.IntegerField()),
                ('image', models.ImageField(max_length=500, upload_to=menu.models.food_image_upload_path)),
                ('discount', models.FloatField(blank=True, help_text='Enter value in %', null=True)),
                ('cuisine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.Cuisine')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.Type')),
            ],
        ),
    ]
