# Generated by Django 2.2.5 on 2020-06-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_breakfastfoods_dinnerfoods_fooddislikes_foodlikes_supperfoods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreakfastFoods',
            new_name='BreakfastFood',
        ),
        migrations.RenameModel(
            old_name='SupperFoods',
            new_name='DinnerFood',
        ),
        migrations.RenameModel(
            old_name='DinnerFoods',
            new_name='SupperFood',
        ),
    ]
