# Generated by Django 2.2.5 on 2020-06-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200622_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='total_orders',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
